name: LA AutoGlass
favicon: null
layout_spectrum: 0.2240143
typography_spectrum: 0.4964158
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Windshield Repair & Auto Glass Replacement Company in Los Angeles'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#032163'
    - '#F9190D'
    - '#908F90'
    - '#910F05'
  brandStrength: 0.9587814
  lightness: 0.8454817
  saturation: 0.9908685
  rhythmicContrast: 0.8643959
purpose: []
